[package]
name = "af-path-walk"
version = "0.1.0"
edition = "2018"
license.workspace = true
authors.workspace = true

[lib]
name = "af_path_walk"
crate-type = ["cdylib"]

[dependencies]
median.workspace = true
strfmt.workspace = true
thiserror.workspace = true
anyhow.workspace = true
regex.workspace = true
ignore.workspace = true
