[package]
name = "af-path-walk"
version = "0.1.0"
edition = "2018"

[lib]
name = "af_path_walk"
crate-type = ["cdylib"]
path = "src/walk.rs"

[dependencies]
median.workspace = true
strfmt.workspace = true
thiserror.workspace = true
anyhow.workspace = true
regex.workspace = true
ignore.workspace = true
