[package]
name = "af-path-template"
version = "0.1.0"
authors = [ "Greg Wuller <greg@afofo.com>" ]
edition = "2018"
license = "MIT"

[lib]
name = "af_path_template"
crate-type = ["cdylib"]

[dependencies]
median = { git = "https://github.com/ngwese/median", rev = "f5a8ad5" }
# median = { path = "${HOME}/proj/median" }
strfmt = "0.2.4"
thiserror = "2.0.12"
anyhow = "1.0.98"
regex = "1.11.1"

[profile.release]
lto = true
panic = "abort"
